/**
 * Real database driver via Prisma. Used only when DB_DRIVER=prisma.
 * Requires `npm install @prisma/client` + `npx prisma generate` first.
 */
export async function createPrismaClient(): Promise<any> {
  // @ts-ignore - @prisma/client is generated by `npm run db:setup`
  const mod = await import('@prisma/client');
  const PrismaClient = (mod as any).PrismaClient;
  return new PrismaClient();
}
