/**
 * Real PostgreSQL/SQLite driver via Prisma. Activated with DB_DRIVER=prisma.
 * Requires `npm run db:setup` first (installs @prisma/client + generates the client).
 * The dynamic import + ts-ignore keep the default (file-store) build working even
 * when @prisma/client is not yet installed.
 */
// @ts-ignore - @prisma/client is generated by `npm run db:setup`
const { PrismaClient } = await import('@prisma/client');
export const prisma: any = new PrismaClient();
